# Generated by Django 3.0.4 on 2020-10-10 07:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=16)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=16)),
                ('description', models.TextField(max_length=1024)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('complete', models.BooleanField(default=False)),
                ('date_complete', models.DateTimeField(blank=True, default=None, null=True)),
                ('_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TaskManager.List')),
            ],
        ),
    ]
