# Generated by Django 3.0.4 on 2020-08-28 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date_complete',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
